# Generated by Django 4.2.6 on 2023-10-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('doj', models.DateField(blank=True, null=True)),
                ('present_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_no', models.CharField(blank=True, max_length=15)),
                ('adhar_no', models.CharField(blank=True, max_length=12)),
                ('epf_no', models.CharField(blank=True, max_length=15)),
                ('esi_no', models.CharField(blank=True, max_length=15)),
                ('pan_no', models.CharField(blank=True, max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('acc_no', models.CharField(blank=True, max_length=20)),
                ('ifse', models.CharField(blank=True, max_length=15)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('bg', models.CharField(blank=True, max_length=5)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('last_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
