# Generated by Django 4.2.6 on 2023-10-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_reg_home', '0002_attendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('monthly_salary', models.CharField(max_length=20)),
                ('gross_salary_ctc', models.CharField(max_length=20)),
                ('employee_type', models.CharField(max_length=100)),
            ],
        ),
    ]
