# Generated by Django 4.2.6 on 2023-10-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_reg_home', '0003_employeesalary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeSalary',
        ),
    ]
