# Generated by Django 4.2.6 on 2023-10-25 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_reg_home', '0007_alter_employeesalary_adv_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalary',
            name='adv_paid_date',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='advance_amount',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='balance_amount',
        ),
        migrations.CreateModel(
            name='SalaryUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_amount', models.IntegerField(blank=True, null=True)),
                ('balance_amount', models.IntegerField(blank=True, null=True)),
                ('adv_paid_date', models.DateField(null=True, unique=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_reg_home.employee')),
            ],
        ),
    ]
