# Generated by Django 4.2.6 on 2023-10-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_reg_home', '0008_remove_employeesalary_adv_paid_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='adv_paid_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='advance_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='balance_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SalaryUpdate',
        ),
    ]
