# Generated by Django 4.2.6 on 2023-10-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_reg_home', '0010_alter_employeesalary_adv_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalary',
            name='adv_paid_date',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='advance_amount',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='balance_amount',
        ),
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
