# Generated by Django 4.2.6 on 2023-10-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_reg_home', '0013_alter_attendence_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendence',
            new_name='Attendance',
        ),
    ]
