# Generated by Django 4.2.6 on 2023-10-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_reg_home', '0014_rename_attendence_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='overtime',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
