# Generated by Django 4.2.6 on 2023-10-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_reg_home', '0017_alter_attendance_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatesalary',
            name='adv_paid_date',
            field=models.DateField(null=True),
        ),
    ]
