# Generated by Django 4.2.6 on 2023-10-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_reg_home', '0018_alter_updatesalary_adv_paid_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeSalary',
        ),
    ]
