# Generated by Django 4.2.6 on 2023-10-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_reg_home', '0020_employeesalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='balance_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
