# Generated by Django 4.2.6 on 2023-10-30 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_reg_home', '0021_employeesalary_balance_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatesalary',
            name='balance_amount',
        ),
    ]
