# Generated by Django 3.2.15 on 2023-12-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_reg_home', '0025_employeesalary_balance_to_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='employee_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
