# Generated by Django 3.2.15 on 2023-12-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_reg_home', '0026_alter_employeesalary_employee_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalary',
            name='balance_to_pay',
        ),
        migrations.AddField(
            model_name='updatesalary',
            name='balance_to_pay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
