# Generated by Django 3.2.15 on 2023-12-28 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_reg_home', '0027_auto_20231228_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatesalary',
            name='balance_to_pay',
        ),
        migrations.CreateModel(
            name='balanceAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_to_pay', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_reg_home.employee')),
            ],
        ),
    ]
