# Generated by Django 3.2.15 on 2023-12-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_reg_home', '0028_auto_20231229_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceamount',
            name='balance_reg_date',
            field=models.DateField(null=True),
        ),
    ]
